services:
  backend:
    build:
      context: ./backend
      target: dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: ./.env.dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - exchange

  engine:
    build:
      context: ./engine
      target: dev
    restart: unless-stopped
    env_file: ./.env.dev
    volumes:
      - ./engine:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
    networks:
      - exchange

  worker:
    build:
      context: ./worker
      target: dev
    restart: unless-stopped
    env_file: ./.env.dev
    volumes:
      - ./worker:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - exchange

  postgres:
    image: timescale/timescaledb:2.28.2-pg17
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: exchange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - exchange

  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - exchange

volumes:
  postgres_data:

networks:
  exchange:
    name: exchange-network
    external: true
