services:
  btc-bot:
    build: ./bot
    restart: unless-stopped
    env_file: .env.prod
    environment:
      MARKET: BTC_USD
      SERVICE_EMAIL: btc.service@paperdrill.dev
      MAX_ORDER_QTY: 0.1
    networks:
      - paperdrill

  sol-bot:
    build: ./bot
    restart: unless-stopped
    env_file: .env.prod
    environment:
      MARKET: SOL_USD
      SERVICE_EMAIL: sol.service@paperdrill.dev
      MAX_ORDER_QTY: 10
    networks:
      - paperdrill

  eth-bot:
    build: ./bot
    restart: unless-stopped
    env_file: .env.prod
    environment:
      MARKET: ETH_USD
      SERVICE_EMAIL: eth.service@paperdrill.dev
      MAX_ORDER_QTY: 1
    networks:
      - paperdrill

networks:
  paperdrill:
    name: paperdrill-network
    external: true
