services:
  btc-bot:
    build: ./
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MARKET: BTC_USD
      BOT_EMAIL: bot.btc@paperdrill.dev
    networks:
      - paperdrill

  sol-bot:
    build: ./
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MARKET: SOL_USD
      BOT_EMAIL: bot.sol@paperdrill.dev
    networks:
      - paperdrill

  eth-bot:
    build: ./
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MARKET: ETH_USD
      BOT_EMAIL: bot.eth@paperdrill.dev
    networks:
      - paperdrill

networks:
  paperdrill:
    name: paperdrill-network
    external: true
